services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbit-cluster
    ports:
      - "8080:15672"
      - "5672:5672"

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USERNAME: postgres
      POSTGRES_DB: messages
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:

networks: 
  my-network:
